export GOPATH="$HOME/.go"
export PATH="$HOME/code/scripts:$HOME/code/utils:$HOME/.local/bin:$HOME/.spicetify:$GOPATH/bin:$HOME/.cargo/bin:$PATH"
export QT_QPA_PLATFORMTHEME="qt5ct" # on X11
#export QT_QPA_PLATFORMTHEME="wayland"
export KRITA_NO_STYLE_OVERRIDE=1
export EDITOR="nvim"
export FZF_DEFAULT_OPTS=" \
--color=bg+:-1,bg:-1,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796"
export VAGRANT_DEFAULT_PROVIDER=libvirt
