gui:
  theme:
    activeBorderColor:
      - '#c4a7e7'
      - bold
    inactiveBorderColor:
      - '#6e6a86'
    optionsTextColor:
      - '#9ccfd8'
    selectedLineBgColor:
      - '#403d52'
    cherryPickedCommitBgColor:
      - '#403d52'
    cherryPickedCommitFgColor:
      - '#f6c177'
      - bold
    markedBaseCommitBgColor:
      - '#403d52'
    markedBaseCommitFgColor:
      - '#9ccfd8'
      - bold
    unstagedChangesColor:
      - '#eb6f92'
    defaultFgColor:
      - '#e0def4'
    searchingActiveBorderColor:
      - '#f6c177'

  authorColors:
    'Adam': '#c4a7e7'
    'adam': '#c4a7e7'
    'Claude': '#ebbcba'
    'claude': '#ebbcba'
    '*': '#9ccfd8'

  branchColors:
    'main': '#c4a7e7'
    'master': '#c4a7e7'
    'develop': '#9ccfd8'
    'feature': '#31748f'
    'feat': '#31748f'
    'fix': '#eb6f92'
    'hotfix': '#eb6f92'
    'bug': '#eb6f92'
    'release': '#f6c177'
    'chore': '#ebbcba'
    'docs': '#9ccfd8'
    'refactor': '#c4a7e7'
    'test': '#f6c177'
