#!/usr/bin/env zsh
# Snapshot what the system rc files contribute to an interactive login shell.
#
# /etc/zprofile -> /etc/profile -> /etc/profile.d/*.sh (and /etc/zshrc for
# non-login shells) cost roughly 25ms per shell. They fork flatpak,
# hostnamectl and id, and none of what they produce differs between shells on
# the same machine. This writes a file that replays the same result with no
# forks at all; ~/.zshenv sources it and sets NO_GLOBAL_RCS.
#
# Re-run this whenever /etc/profile or /etc/profile.d changes. ~/.zshrc does
# that automatically in the background.

emulate -L zsh
zmodload zsh/datetime
zmodload zsh/zpty
setopt extended_glob no_unset

local out=${1:-$HOME/.cache/zsh/system-env.zsh}
local A=/__sysenv_pre__ B=/__sysenv_post__
# A realistic PATH: scripts probe for flatpak, lesspipe and hostnamectl, and
# must find them or the snapshot will be missing what they contribute.
local PROBE=$A:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:$B
# An empty ZDOTDIR keeps the user's own rc files out of the probe, so the
# snapshot captures the /etc contribution and nothing else.
local empty=$(mktemp -d) || return 1
: >$empty/.zshrc  # keep zsh-newuser-install from firing in the probe shell
local tmp=${out}.$$
trap "rm -rf ${(q)empty} ${(q)tmp}" EXIT INT TERM

# $1: extra zsh flags, $2: script to run in the probe shell
__probe() {
	env -i HOME=$HOME USER=${USER:-$LOGNAME} PATH=$PROBE ZDOTDIR=$empty \
		/usr/bin/zsh $=1 -c $2 2>/dev/null
}

# Same, but with a pty on stdin. Several /etc scripts (colorls.sh above all)
# bail out early with `[ ! -t 0 ] && return`, so without a tty the snapshot
# would silently miss the aliases they define.
__probe_tty() {
	local name=sysenv_probe line out=
	zpty $name "env -i HOME=${(q)HOME} USER=${(q)${USER:-$LOGNAME}} PATH=${(q)PROBE} ZDOTDIR=${(q)empty} TERM=${(q)${TERM:-xterm-256color}} /usr/bin/zsh $1 -c ${(q)2}"
	while zpty -r $name line; do out+=$line; done
	zpty -d $name 2>/dev/null
	out=${out//$'\r'/}
	# Strip the terminal escapes a tty session emits around the output.
	out=${out//$'\e'\[[0-9;?]#[a-zA-Z]/}
	out=${out//$'\e'\][^$'\a'$'\e']#($'\a'|$'\e'\\)/}
	print -r -- $out
}

local -a base after afterpath addpre addpost
local -a basealias afteralias basefunc afterfunc newfns
base=(   ${(f)"$(__probe '-f'    'typeset -px')"} )
after=(  ${(f)"$(__probe '-l'    'typeset -px')"} )
afterpath=( ${(s.:.)"$(__probe '-l' 'print -r -- $PATH')"} )
basealias=(  ${(f)"$(__probe_tty '-f -i' 'alias -L')"} )
afteralias=( ${(f)"$(__probe_tty '-l -i' 'alias -L')"} )
basefunc=(   ${(f)"$(__probe_tty '-f -i' 'print -l -- ${(ok)functions}')"} )
afterfunc=(  ${(f)"$(__probe_tty '-l -i' 'print -l -- ${(ok)functions}')"} )

if (( ! $#after )); then
	print -u2 "gen-sysenv: probe shell produced nothing; refusing to write $out"
	return 1
fi

# Split the system's PATH additions into those it puts before the PATH we
# handed it and those it appends, so they can be re-applied around any PATH.
local ia=${afterpath[(ie)$A]} ib=${afterpath[(ie)$B]}
(( ia > 1 ))             && addpre=(  ${afterpath[1,ia-1]}  )
(( ib < $#afterpath ))   && addpost=( ${afterpath[ib+1,-1]} )

# Functions worth carrying over: skip completion internals and anything the
# integration scripts re-define for themselves when sourced below.
local fn
for fn in $afterfunc; do
	(( ${basefunc[(Ie)$fn]} )) && continue
	[[ $fn == (_*|pathmunge|__vte_*|__wezterm_*|zsh-newuser-install|clear) ]] && continue
	newfns+=($fn)
done

mkdir -p ${out:h} || return 1
{
	print '# Generated by gen-sysenv.zsh. Replays what /etc/zprofile,'
	print '# /etc/profile and /etc/profile.d/*.sh set up, without their forks.'
	print '# Sourced from ~/.zshenv, which then skips the global rc files.'
	print "# Built $(strftime '%Y-%m-%d %H:%M' $EPOCHSECONDS) on ${HOST}."
	print ''

	local line
	for line in $after; do
		(( ${base[(Ie)$line]} )) && continue
		case $line in
			# Per-shell state, and values the user's own config sets later.
			*' PWD='*|*' OLDPWD='*|*' SHLVL='*|*' _='*) continue ;;
			*' TERM='*|*' HOME='*|*' USER='*|*' LOGNAME='*) continue ;;
			*' PATH='*|*' path='*|*' HISTSIZE='*|*' HISTCONTROL='*|*' EDITOR='*) continue ;;
			# Must be this shell's own tty, not the one the snapshot was built on.
			*' GPG_TTY='*) continue ;;
		esac
		print -r -- $line
	done

	print ''
	print '# PATH entries the system rc files contribute, applied idempotently.'
	local nm e str
	for nm in pre post; do
		str=''
		for e in ${(P)${:-add$nm}}; do
			[[ -n $e ]] && str+=" ${(q)e}"
		done
		print -r -- "typeset -ga __sysenv_$nm=($str )"
	done
	print 'path=( ${__sysenv_pre:|path} $path ${__sysenv_post:|path} )'
	print 'typeset -U path PATH'

	print ''
	print '# Aliases from colorls.sh, colorgrep.sh, which2.sh and friends.'
	local a
	for a in $afteralias; do
		(( ${basealias[(Ie)$a]} )) && continue
		print -r -- $a
	done

	if (( $#newfns )); then
		print ''
		print '# Functions from gawk.sh and friends.'
		__probe_tty '-l -i' "functions -- ${(j: :)newfns}"
	fi

	print ''
	print '# Shell integration and key bindings the /etc files install.'
	print '# gnupg2.sh forks $(tty) for this; zsh already knows it as $TTY.'
	print '# Non-interactive shells have no tty and do not need it.'
	print '[[ -n $TTY ]] && export GPG_TTY=$TTY'
	print '[[ -r /etc/profile.d/wezterm.sh ]] && source /etc/profile.d/wezterm.sh'
	print 'bindkey " " magic-space'
} >| $tmp || return 1

mv -f $tmp $out && print "gen-sysenv: wrote $out"
